# Generated by Django 4.1.12 on 2023-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tML", "0002_database"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dataset_id", models.IntegerField()),
                ("target_column", models.CharField(max_length=100)),
                ("feature_columns", models.TextField()),
                ("task_type", models.CharField(max_length=50)),
                ("model_algorithms", models.TextField()),
                ("evaluation_methods", models.TextField()),
                ("parameters", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="MLModel",
        ),
    ]
